### ISSUE TITLE
Compiler Explorer site links don't work

### ISSUE THREAD

**Issue by mattgodbolt** [DaemonSnake/gcc-7.1.0-abriviated-cpp-lambda#3]
Hi there! Awesome to see the CE example site of your proposal. Just a note: the "Share" doesn't work as the URL contains the internal IP and port of your site. I'm not sure how you're running your CE node, but I can help make it work if you need it!

**Comment by DaemonSnake** [comment]
I see... I'm just running a simple amazon EC2 server with a dot.tk domain that forward to the public IP of the instance, as for CE itself i'm using pm2 to run CE. 
If you have suggestions I'm interested.
A small precision, it's not actually my proposal, it's Barry Revzin's (barry.revzin@gmail.com) proposal.

**Comment by DaemonSnake** [comment]
corrected
